exclude_paths:
  - '**/*.sql' # Codacy does not recognise MySQL
  - '**/*.js'  # Codacy does not recognise userscript-specific function practices (e.g. GreaseMonkey GM_... functions), nor addon-specific objects (e.g. chrome)
  - '*.md'     # Man pages require multiple top-level headers, and the other markdown documents often require 'duplicate' headers.
  - '**/*.md'
