language: c++

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: clang
      env: BADGE=linux # To allow OS-wise badges - see https://github.com/travis-ci/travis-ci/issues/9579

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then  sudo apt update  &&  sudo apt install -y mariadb-client-10.1 mariadb-client-core-10.1 default-libmysqlclient-dev qt5-default libqt5widgets5;  fi # libcompsky direct dependencies
  - git clone https://github.com/NotCompsky/libcompsky
  - mkdir libcompsky/build  &&  cd libcompsky/build  &&  cmake .. &&  sudo make install  &&  cd ../..  # Build libcompsky
  - if [ $TRAVIS_OS_NAME == linux ]; then  sudo apt install curl wget golang libcurl4-openssl-dev default-libmysqlclient-dev rapidjson-dev libboost-regex-dev pandoc qt5-default libqt5widgets5 libqt5charts5 libqt5charts5-dev;  fi # rscraper direct dependencies

script:
  - mkdir -p 3rdparty/include 3rdparty/src 3rdparty/cmake  &&   wget -O 3rdparty/include/libb64.h https://raw.githubusercontent.com/cburstedde/libsc/b19431d87224c0d9e89e16f0f8dc381a9e11a1ea/libb64/libb64.h  &&  wget -O 3rdparty/src/base64.c https://raw.githubusercontent.com/cburstedde/libsc/76db2bce7a2f78d789fe3f13234be752b24c5404/libb64/cencode.c
  - mkdir build  &&  cd build  &&  cmake .. -DBUILD_PACKAGES=1 -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=$(dpkg --print-architecture)  &&  make package

