#!/bin/bash


CATEGORY="$1"
TAGS=`echo "${@:2}" | sed "s/ /','/g"`

mysql --user="rscraper++" --password="$PASSWORD" --database="rscraper" --execute "INSERT IGNORE INTO category (name) values('$CATEGORY');"

mysql --user="rscraper++" --password="$PASSWORD" --database="rscraper" --execute "
INSERT INTO tag2category (category_id, tag_id)
SELECT c.id, t.id
FROM category c JOIN tag t
WHERE (c.name = '$CATEGORY') AND (t.name in ('$TAGS'))
;
"
