#!/bin/bash


TAG="$1"
SUBREDDITS=`echo "${@:2}" | sed "s/ /','/g"`

mysql --user="rscraper++" --password="$PASSWORD" --database="rscraper" --execute "INSERT IGNORE INTO tag (name) values('$TAG');"

if [[ $# -eq 2 ]]; then
mysql --user="rscraper++" --password="$PASSWORD" --database="rscraper" --execute "
INSERT IGNORE INTO subreddit2tag (tag_id, subreddit_id)
SELECT t.id, s.id
FROM tag t JOIN subreddit s
WHERE (t.name = '$TAG') AND (s.name LIKE '$SUBREDDITS')
;
"
else # gt
mysql --user="rscraper++" --password="$PASSWORD" --database="rscraper" --execute "
INSERT IGNORE INTO subreddit2tag (tag_id, subreddit_id)
SELECT t.id, s.id
FROM tag t JOIN subreddit s
WHERE (t.name = '$TAG') AND (s.name in ('$SUBREDDITS'))
;
"
fi
