version: 2
general:
  artifacts:
    - "packages"
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Update Apt Cache
          command: 'apt update'

      - run:
          name: libcompsky - Install git
          command: 'apt install -y git'
      - run:
          name: libcompsky - Download
          command: 'git clone https://github.com/NotCompsky/libcompsky'
      - run:
          name: libcompsky - Install SQL Client Dev
          command: 'apt install -y mariadb-client default-libmysqlclient-dev qt5-default libqt5widgets5 libqt5charts5 libqt5charts5-dev'
      - run:
          name: libcompsky - Install GCC
          command: 'apt install -y g++'
      - run:
          name: libcompsky - Install CMake
          command: 'apt install -y cmake'
      - run:
          name: libcompsky - Generate build files
          command: 'mkdir libcompsky/build  &&  cd libcompsky/build  &&  cmake .. -DMYSQL_UNDER_DIR=/usr/include/mysql -DMYSQL_UNDER_DIR_OVERRIDE=1  &&  make  &&  make install'

      - run:
          name: Install Curl and WGet
          command: 'apt install -y curl wget'
      - run:
          name: Install Dependencies
          command: 'apt install -y golang libb64-dev libcurl4-openssl-dev default-libmysqlclient-dev rapidjson-dev libboost-regex-dev pandoc'
      - run:
          name: mkdirs
          command: 'mkdir -p build 3rdparty/include 3rdparty/src 3rdparty/cmake'
      - run:
          name: WGet libb64
          command: 'wget -O 3rdparty/include/libb64.h https://raw.githubusercontent.com/cburstedde/libsc/b19431d87224c0d9e89e16f0f8dc381a9e11a1ea/libb64/libb64.h  &&  wget -O 3rdparty/src/base64.c https://raw.githubusercontent.com/cburstedde/libsc/76db2bce7a2f78d789fe3f13234be752b24c5404/libb64/cencode.c'
      - run:
          name: Build
          command: 'cd build  &&  cmake .. -DBUILD_PACKAGES=1 -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=$(dpkg --print-architecture)  &&  cmake --build . --target package'
      - run:
          name: Move packages to artifact storage
          command: 'mkdir packages  &&  mv build/pkg/*.deb packages/'
      - store_artifacts:
          path: "packages"
